<?php

namespace Repository;

/**
 * CertificadoAprovacaoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CertificadoAprovacaoRepository extends \Doctrine\ORM\EntityRepository
{
}
