<?php

namespace Repository;

/**
 * EPIRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EPIRepository extends \Doctrine\ORM\EntityRepository
{

}
